#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
#[serde(default)]
pub struct Block2Params {
    // Block 2 input geometry + color + filters
    pub block2_input_x_displace: f32,
    pub block2_input_y_displace: f32,
    pub block2_input_z_displace: f32,
    pub block2_input_rotate: f32,
    pub block2_input_hsb_attenuate_h: f32,
    pub block2_input_hsb_attenuate_s: f32,
    pub block2_input_hsb_attenuate_b: f32,
    pub block2_input_posterize: f32,
    pub block2_input_kaleidoscope_amount: f32,
    pub block2_input_kaleidoscope_slice: f32,
    pub block2_input_blur_amount: f32,
    pub block2_input_blur_radius: f32,
    pub block2_input_sharpen_amount: f32,
    pub block2_input_sharpen_radius: f32,
    pub block2_input_filters_boost: f32,
    pub block2_input_h_mirror: bool,
    pub block2_input_v_mirror: bool,
    pub block2_input_h_flip: bool,
    pub block2_input_v_flip: bool,
    pub block2_input_hue_invert: bool,
    pub block2_input_saturation_invert: bool,
    pub block2_input_bright_invert: bool,
    pub block2_input_rgb_invert: bool,
    pub block2_input_geo_overflow: i32,
    pub block2_input_solarize: bool,
    pub block2_input_posterize_switch: bool,
    pub block2_input_hd_aspect_on: bool,

    // FB2 mix + key
    pub fb2_mix_amount: f32,
    pub fb2_key_value_r: f32,
    pub fb2_key_value_g: f32,
    pub fb2_key_value_b: f32,
    pub fb2_key_threshold: f32,
    pub fb2_key_soft: f32,
    pub fb2_mix_type: i32,
    pub fb2_mix_overflow: i32,
    pub fb2_key_mode: i32,
    pub fb2_key_order: i32,

    // FB2 geometry
    pub fb2_x_displace: f32,
    pub fb2_y_displace: f32,
    pub fb2_z_displace: f32,
    pub fb2_rotate: f32,
    pub fb2_shear_xx: f32,
    pub fb2_shear_xy: f32,
    pub fb2_shear_yx: f32,
    pub fb2_shear_yy: f32,
    pub fb2_kaleidoscope_amount: f32,
    pub fb2_kaleidoscope_slice: f32,
    pub fb2_h_mirror: bool,
    pub fb2_v_mirror: bool,
    pub fb2_h_flip: bool,
    pub fb2_v_flip: bool,
    pub fb2_rotate_mode: i32,
    pub fb2_geo_overflow: i32,

    // FB2 color
    pub fb2_hsb_offset_h: f32,
    pub fb2_hsb_offset_s: f32,
    pub fb2_hsb_offset_b: f32,
    pub fb2_hsb_attenuate_h: f32,
    pub fb2_hsb_attenuate_s: f32,
    pub fb2_hsb_attenuate_b: f32,
    pub fb2_hsb_powmap_h: f32,
    pub fb2_hsb_powmap_s: f32,
    pub fb2_hsb_powmap_b: f32,
    pub fb2_hue_shaper: f32,
    pub fb2_posterize: f32,
    pub fb2_posterize_invert: f32,
    pub fb2_posterize_switch: bool,
    pub fb2_hue_invert: bool,
    pub fb2_saturation_invert: bool,
    pub fb2_bright_invert: bool,
    pub fb2_rgb_invert: bool,

    // FB2 filters
    pub fb2_blur_amount: f32,
    pub fb2_blur_radius: f32,
    pub fb2_sharpen_amount: f32,
    pub fb2_sharpen_radius: f32,
    pub fb2_temporal1_amount: f32,
    pub fb2_temporal1_resonance: f32,
    pub fb2_temporal2_amount: f32,
    pub fb2_temporal2_resonance: f32,
    pub fb2_filters_boost: f32,

    // FB2 delay
    pub fb2_delay_time: u32,
    pub fb2_delay_time_sync: bool,
    pub fb2_delay_time_division: i32,

    // Input selection (0=block1, 1=input1, 2=input2)
    pub block2_input_select: i32,
}

impl Default for Block2Params {
    fn default() -> Self {
        Self {
            block2_input_x_displace: 0.0,
            block2_input_y_displace: 0.0,
            block2_input_z_displace: 1.0,
            block2_input_rotate: 0.0,
            block2_input_hsb_attenuate_h: 1.0,
            block2_input_hsb_attenuate_s: 1.0,
            block2_input_hsb_attenuate_b: 1.0,
            block2_input_posterize: 16.0,
            block2_input_kaleidoscope_amount: 0.0,
            block2_input_kaleidoscope_slice: 0.0,
            block2_input_blur_amount: 0.0,
            block2_input_blur_radius: 1.0,
            block2_input_sharpen_amount: 0.0,
            block2_input_sharpen_radius: 1.0,
            block2_input_filters_boost: 0.0,
            block2_input_h_mirror: false,
            block2_input_v_mirror: false,
            block2_input_h_flip: false,
            block2_input_v_flip: false,
            block2_input_hue_invert: false,
            block2_input_saturation_invert: false,
            block2_input_bright_invert: false,
            block2_input_rgb_invert: false,
            block2_input_geo_overflow: 0,
            block2_input_solarize: false,
            block2_input_posterize_switch: false,
            block2_input_hd_aspect_on: false,

            fb2_mix_amount: 0.0,
            fb2_key_value_r: 0.0,
            fb2_key_value_g: 0.0,
            fb2_key_value_b: 0.0,
            fb2_key_threshold: 1.0,
            fb2_key_soft: 0.0,
            fb2_mix_type: 0,
            fb2_mix_overflow: 0,
            fb2_key_mode: 0,
            fb2_key_order: 0,

            fb2_x_displace: 0.0,
            fb2_y_displace: 0.0,
            fb2_z_displace: 1.0,
            fb2_rotate: 0.0,
            fb2_shear_xx: 1.0,
            fb2_shear_xy: 0.0,
            fb2_shear_yx: 0.0,
            fb2_shear_yy: 1.0,
            fb2_kaleidoscope_amount: 0.0,
            fb2_kaleidoscope_slice: 0.0,
            fb2_h_mirror: false,
            fb2_v_mirror: false,
            fb2_h_flip: false,
            fb2_v_flip: false,
            fb2_rotate_mode: 0,
            fb2_geo_overflow: 0,

            fb2_hsb_offset_h: 0.0,
            fb2_hsb_offset_s: 0.0,
            fb2_hsb_offset_b: 0.0,
            fb2_hsb_attenuate_h: 1.0,
            fb2_hsb_attenuate_s: 1.0,
            fb2_hsb_attenuate_b: 1.0,
            fb2_hsb_powmap_h: 1.0,
            fb2_hsb_powmap_s: 1.0,
            fb2_hsb_powmap_b: 1.0,
            fb2_hue_shaper: 1.0,
            fb2_posterize: 16.0,
            fb2_posterize_invert: 1.0 / 16.0,
            fb2_posterize_switch: false,
            fb2_hue_invert: false,
            fb2_saturation_invert: false,
            fb2_bright_invert: false,
            fb2_rgb_invert: false,

            fb2_blur_amount: 0.0,
            fb2_blur_radius: 1.0,
            fb2_sharpen_amount: 0.0,
            fb2_sharpen_radius: 1.0,
            fb2_temporal1_amount: 0.0,
            fb2_temporal1_resonance: 0.0,
            fb2_temporal2_amount: 0.0,
            fb2_temporal2_resonance: 0.0,
            fb2_filters_boost: 0.0,

            fb2_delay_time: 1,
            fb2_delay_time_sync: false,
            fb2_delay_time_division: 2,

            block2_input_select: 0,
        }
    }
}
