#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
#[serde(default)]
pub struct Block1Params {
    // CH1 geometry + color + filters
    pub ch1_x_displace: f32,
    pub ch1_y_displace: f32,
    pub ch1_z_displace: f32,
    pub ch1_rotate: f32,
    pub ch1_hsb_attenuate_h: f32,
    pub ch1_hsb_attenuate_s: f32,
    pub ch1_hsb_attenuate_b: f32,
    pub ch1_posterize: f32,
    pub ch1_kaleidoscope_amount: f32,
    pub ch1_kaleidoscope_slice: f32,
    pub ch1_blur_amount: f32,
    pub ch1_blur_radius: f32,
    pub ch1_sharpen_amount: f32,
    pub ch1_sharpen_radius: f32,
    pub ch1_filters_boost: f32,
    pub ch1_h_mirror: bool,
    pub ch1_v_mirror: bool,
    pub ch1_h_flip: bool,
    pub ch1_v_flip: bool,
    pub ch1_hue_invert: bool,
    pub ch1_saturation_invert: bool,
    pub ch1_bright_invert: bool,
    pub ch1_rgb_invert: bool,
    pub ch1_geo_overflow: i32,
    pub ch1_solarize: bool,
    pub ch1_posterize_switch: bool,
    pub ch1_hd_aspect_on: bool,
    pub ch1_input_select: i32,

    // CH2 mix + key
    pub ch2_mix_amount: f32,
    pub ch2_key_value_r: f32,
    pub ch2_key_value_g: f32,
    pub ch2_key_value_b: f32,
    pub ch2_key_threshold: f32,
    pub ch2_key_soft: f32,
    pub ch2_mix_type: i32,
    pub ch2_mix_overflow: i32,
    pub ch2_key_order: i32,
    pub ch2_key_mode: i32,

    // CH2 geometry + color + filters
    pub ch2_x_displace: f32,
    pub ch2_y_displace: f32,
    pub ch2_z_displace: f32,
    pub ch2_rotate: f32,
    pub ch2_hsb_attenuate_h: f32,
    pub ch2_hsb_attenuate_s: f32,
    pub ch2_hsb_attenuate_b: f32,
    pub ch2_posterize: f32,
    pub ch2_kaleidoscope_amount: f32,
    pub ch2_kaleidoscope_slice: f32,
    pub ch2_blur_amount: f32,
    pub ch2_blur_radius: f32,
    pub ch2_sharpen_amount: f32,
    pub ch2_sharpen_radius: f32,
    pub ch2_filters_boost: f32,
    pub ch2_h_mirror: bool,
    pub ch2_v_mirror: bool,
    pub ch2_h_flip: bool,
    pub ch2_v_flip: bool,
    pub ch2_hue_invert: bool,
    pub ch2_saturation_invert: bool,
    pub ch2_bright_invert: bool,
    pub ch2_rgb_invert: bool,
    pub ch2_geo_overflow: i32,
    pub ch2_solarize: bool,
    pub ch2_posterize_switch: bool,
    pub ch2_hd_aspect_on: bool,
    pub ch2_input_select: i32,

    // FB1 mix + key
    pub fb1_mix_amount: f32,
    pub fb1_key_value_r: f32,
    pub fb1_key_value_g: f32,
    pub fb1_key_value_b: f32,
    pub fb1_key_threshold: f32,
    pub fb1_key_soft: f32,
    pub fb1_mix_type: i32,
    pub fb1_mix_overflow: i32,
    pub fb1_key_order: i32,
    pub fb1_key_mode: i32,

    // FB1 geometry
    pub fb1_x_displace: f32,
    pub fb1_y_displace: f32,
    pub fb1_z_displace: f32,
    pub fb1_rotate: f32,
    pub fb1_shear_xx: f32,
    pub fb1_shear_xy: f32,
    pub fb1_shear_yx: f32,
    pub fb1_shear_yy: f32,
    pub fb1_kaleidoscope_amount: f32,
    pub fb1_kaleidoscope_slice: f32,
    pub fb1_h_mirror: bool,
    pub fb1_v_mirror: bool,
    pub fb1_h_flip: bool,
    pub fb1_v_flip: bool,
    pub fb1_rotate_mode: i32,
    pub fb1_geo_overflow: i32,

    // FB1 color
    pub fb1_hsb_offset_h: f32,
    pub fb1_hsb_offset_s: f32,
    pub fb1_hsb_offset_b: f32,
    pub fb1_hsb_attenuate_h: f32,
    pub fb1_hsb_attenuate_s: f32,
    pub fb1_hsb_attenuate_b: f32,
    pub fb1_hsb_powmap_h: f32,
    pub fb1_hsb_powmap_s: f32,
    pub fb1_hsb_powmap_b: f32,
    pub fb1_hue_shaper: f32,
    pub fb1_posterize: f32,
    pub fb1_posterize_invert: f32,
    pub fb1_hue_invert: bool,
    pub fb1_saturation_invert: bool,
    pub fb1_bright_invert: bool,
    pub fb1_posterize_switch: bool,

    // FB1 filters
    pub fb1_blur_amount: f32,
    pub fb1_blur_radius: f32,
    pub fb1_sharpen_amount: f32,
    pub fb1_sharpen_radius: f32,
    pub fb1_temporal1_amount: f32,
    pub fb1_temporal1_resonance: f32,
    pub fb1_temporal2_amount: f32,
    pub fb1_temporal2_resonance: f32,
    pub fb1_filters_boost: f32,

    // FB1 delay
    pub fb1_delay_time: u32,
    pub fb1_delay_time_sync: bool,
    pub fb1_delay_time_division: i32,
}

impl Default for Block1Params {
    fn default() -> Self {
        Self {
            ch1_x_displace: 0.0,
            ch1_y_displace: 0.0,
            ch1_z_displace: 1.0,
            ch1_rotate: 0.0,
            ch1_hsb_attenuate_h: 1.0,
            ch1_hsb_attenuate_s: 1.0,
            ch1_hsb_attenuate_b: 1.0,
            ch1_posterize: 16.0,
            ch1_kaleidoscope_amount: 0.0,
            ch1_kaleidoscope_slice: 0.0,
            ch1_blur_amount: 0.0,
            ch1_blur_radius: 1.0,
            ch1_sharpen_amount: 0.0,
            ch1_sharpen_radius: 1.0,
            ch1_filters_boost: 0.0,
            ch1_h_mirror: false,
            ch1_v_mirror: false,
            ch1_h_flip: false,
            ch1_v_flip: false,
            ch1_hue_invert: false,
            ch1_saturation_invert: false,
            ch1_bright_invert: false,
            ch1_rgb_invert: false,
            ch1_geo_overflow: 0,
            ch1_solarize: false,
            ch1_posterize_switch: false,
            ch1_hd_aspect_on: false,
            ch1_input_select: 0,

            ch2_mix_amount: 0.0,
            ch2_key_value_r: 0.0,
            ch2_key_value_g: 0.0,
            ch2_key_value_b: 0.0,
            ch2_key_threshold: 1.0,
            ch2_key_soft: 0.0,
            ch2_mix_type: 0,
            ch2_mix_overflow: 0,
            ch2_key_order: 0,
            ch2_key_mode: 0,

            ch2_x_displace: 0.0,
            ch2_y_displace: 0.0,
            ch2_z_displace: 1.0,
            ch2_rotate: 0.0,
            ch2_hsb_attenuate_h: 1.0,
            ch2_hsb_attenuate_s: 1.0,
            ch2_hsb_attenuate_b: 1.0,
            ch2_posterize: 16.0,
            ch2_kaleidoscope_amount: 0.0,
            ch2_kaleidoscope_slice: 0.0,
            ch2_blur_amount: 0.0,
            ch2_blur_radius: 1.0,
            ch2_sharpen_amount: 0.0,
            ch2_sharpen_radius: 1.0,
            ch2_filters_boost: 0.0,
            ch2_h_mirror: false,
            ch2_v_mirror: false,
            ch2_h_flip: false,
            ch2_v_flip: false,
            ch2_hue_invert: false,
            ch2_saturation_invert: false,
            ch2_bright_invert: false,
            ch2_rgb_invert: false,
            ch2_geo_overflow: 0,
            ch2_solarize: false,
            ch2_posterize_switch: false,
            ch2_hd_aspect_on: false,
            ch2_input_select: 1,

            fb1_mix_amount: 0.0,
            fb1_key_value_r: 0.0,
            fb1_key_value_g: 0.0,
            fb1_key_value_b: 0.0,
            fb1_key_threshold: 1.0,
            fb1_key_soft: 0.0,
            fb1_mix_type: 0,
            fb1_mix_overflow: 0,
            fb1_key_order: 0,
            fb1_key_mode: 0,

            fb1_x_displace: 0.0,
            fb1_y_displace: 0.0,
            fb1_z_displace: 1.0,
            fb1_rotate: 0.0,
            fb1_shear_xx: 1.0,
            fb1_shear_xy: 0.0,
            fb1_shear_yx: 0.0,
            fb1_shear_yy: 1.0,
            fb1_kaleidoscope_amount: 0.0,
            fb1_kaleidoscope_slice: 0.0,
            fb1_h_mirror: false,
            fb1_v_mirror: false,
            fb1_h_flip: false,
            fb1_v_flip: false,
            fb1_rotate_mode: 0,
            fb1_geo_overflow: 0,

            fb1_hsb_offset_h: 0.0,
            fb1_hsb_offset_s: 0.0,
            fb1_hsb_offset_b: 0.0,
            fb1_hsb_attenuate_h: 1.0,
            fb1_hsb_attenuate_s: 1.0,
            fb1_hsb_attenuate_b: 1.0,
            fb1_hsb_powmap_h: 1.0,
            fb1_hsb_powmap_s: 1.0,
            fb1_hsb_powmap_b: 1.0,
            fb1_hue_shaper: 1.0,
            fb1_posterize: 16.0,
            fb1_posterize_invert: 1.0 / 16.0,
            fb1_hue_invert: false,
            fb1_saturation_invert: false,
            fb1_bright_invert: false,
            fb1_posterize_switch: false,

            fb1_blur_amount: 0.0,
            fb1_blur_radius: 1.0,
            fb1_sharpen_amount: 0.0,
            fb1_sharpen_radius: 1.0,
            fb1_temporal1_amount: 0.0,
            fb1_temporal1_resonance: 0.0,
            fb1_temporal2_amount: 0.0,
            fb1_temporal2_resonance: 0.0,
            fb1_filters_boost: 0.0,

            fb1_delay_time: 1,
            fb1_delay_time_sync: false,
            fb1_delay_time_division: 2,
        }
    }
}
