#[derive(Debug, Clone, Copy, serde::Serialize, serde::Deserialize)]
#[serde(default)]
pub struct Block3Params {
    // Block 1 output geometry
    pub block1_x_displace: f32,
    pub block1_y_displace: f32,
    pub block1_z_displace: f32,
    pub block1_rotate: f32,
    pub block1_shear_xx: f32,
    pub block1_shear_xy: f32,
    pub block1_shear_yx: f32,
    pub block1_shear_yy: f32,
    pub block1_kaleidoscope_amount: f32,
    pub block1_kaleidoscope_slice: f32,
    pub block1_h_mirror: bool,
    pub block1_v_mirror: bool,
    pub block1_rotate_mode: i32,
    pub block1_geo_overflow: i32,
    pub block1_h_flip: bool,
    pub block1_v_flip: bool,

    // Block 1 colorize
    pub block1_colorize_switch: bool,
    pub block1_colorize_hsb_rgb: i32,
    pub block1_colorize_band1_h: f32,
    pub block1_colorize_band1_s: f32,
    pub block1_colorize_band1_b: f32,
    pub block1_colorize_band2_h: f32,
    pub block1_colorize_band2_s: f32,
    pub block1_colorize_band2_b: f32,
    pub block1_colorize_band3_h: f32,
    pub block1_colorize_band3_s: f32,
    pub block1_colorize_band3_b: f32,
    pub block1_colorize_band4_h: f32,
    pub block1_colorize_band4_s: f32,
    pub block1_colorize_band4_b: f32,
    pub block1_colorize_band5_h: f32,
    pub block1_colorize_band5_s: f32,
    pub block1_colorize_band5_b: f32,

    // Block 1 filters & dither
    pub block1_blur_amount: f32,
    pub block1_blur_radius: f32,
    pub block1_sharpen_amount: f32,
    pub block1_sharpen_radius: f32,
    pub block1_filters_boost: f32,
    pub block1_dither: f32,
    pub block1_dither_switch: bool,
    pub block1_dither_type: i32,

    // Block 2 output geometry
    pub block2_x_displace: f32,
    pub block2_y_displace: f32,
    pub block2_z_displace: f32,
    pub block2_rotate: f32,
    pub block2_shear_xx: f32,
    pub block2_shear_xy: f32,
    pub block2_shear_yx: f32,
    pub block2_shear_yy: f32,
    pub block2_kaleidoscope_amount: f32,
    pub block2_kaleidoscope_slice: f32,
    pub block2_h_mirror: bool,
    pub block2_v_mirror: bool,
    pub block2_rotate_mode: i32,
    pub block2_geo_overflow: i32,
    pub block2_h_flip: bool,
    pub block2_v_flip: bool,

    // Block 2 colorize
    pub block2_colorize_switch: bool,
    pub block2_colorize_hsb_rgb: i32,
    pub block2_colorize_band1_h: f32,
    pub block2_colorize_band1_s: f32,
    pub block2_colorize_band1_b: f32,
    pub block2_colorize_band2_h: f32,
    pub block2_colorize_band2_s: f32,
    pub block2_colorize_band2_b: f32,
    pub block2_colorize_band3_h: f32,
    pub block2_colorize_band3_s: f32,
    pub block2_colorize_band3_b: f32,
    pub block2_colorize_band4_h: f32,
    pub block2_colorize_band4_s: f32,
    pub block2_colorize_band4_b: f32,
    pub block2_colorize_band5_h: f32,
    pub block2_colorize_band5_s: f32,
    pub block2_colorize_band5_b: f32,

    // Block 2 filters & dither
    pub block2_blur_amount: f32,
    pub block2_blur_radius: f32,
    pub block2_sharpen_amount: f32,
    pub block2_sharpen_radius: f32,
    pub block2_filters_boost: f32,
    pub block2_dither: f32,
    pub block2_dither_switch: bool,
    pub block2_dither_type: i32,

    // Matrix mixer
    pub matrix_mix_type: i32,
    pub matrix_mix_overflow: i32,
    pub matrix_mix_r_to_r: f32,
    pub matrix_mix_r_to_g: f32,
    pub matrix_mix_r_to_b: f32,
    pub matrix_mix_g_to_r: f32,
    pub matrix_mix_g_to_g: f32,
    pub matrix_mix_g_to_b: f32,
    pub matrix_mix_b_to_r: f32,
    pub matrix_mix_b_to_g: f32,
    pub matrix_mix_b_to_b: f32,

    // Final mix
    pub final_mix_amount: f32,
    pub final_key_value_r: f32,
    pub final_key_value_g: f32,
    pub final_key_value_b: f32,
    pub final_key_threshold: f32,
    pub final_key_soft: f32,
    pub final_mix_type: i32,
    pub final_mix_overflow: i32,
    pub final_key_order: i32,
    pub final_key_mode: i32,

    // Final dither
    pub final_dither: f32,
    pub final_dither_switch: bool,
    pub final_dither_type: i32,
}

impl Default for Block3Params {
    fn default() -> Self {
        Self {
            block1_x_displace: 0.0,
            block1_y_displace: 0.0,
            block1_z_displace: 1.0,
            block1_rotate: 0.0,
            block1_shear_xx: 1.0,
            block1_shear_xy: 0.0,
            block1_shear_yx: 0.0,
            block1_shear_yy: 1.0,
            block1_kaleidoscope_amount: 0.0,
            block1_kaleidoscope_slice: 0.0,
            block1_h_mirror: false,
            block1_v_mirror: false,
            block1_rotate_mode: 0,
            block1_geo_overflow: 0,
            block1_h_flip: false,
            block1_v_flip: false,

            block1_colorize_switch: false,
            block1_colorize_hsb_rgb: 0,
            block1_colorize_band1_h: 0.0,
            block1_colorize_band1_s: 0.0,
            block1_colorize_band1_b: 0.0,
            block1_colorize_band2_h: 0.0,
            block1_colorize_band2_s: 0.0,
            block1_colorize_band2_b: 0.0,
            block1_colorize_band3_h: 0.0,
            block1_colorize_band3_s: 0.0,
            block1_colorize_band3_b: 0.0,
            block1_colorize_band4_h: 0.0,
            block1_colorize_band4_s: 0.0,
            block1_colorize_band4_b: 0.0,
            block1_colorize_band5_h: 0.0,
            block1_colorize_band5_s: 0.0,
            block1_colorize_band5_b: 0.0,

            block1_blur_amount: 0.0,
            block1_blur_radius: 1.0,
            block1_sharpen_amount: 0.0,
            block1_sharpen_radius: 1.0,
            block1_filters_boost: 0.0,
            block1_dither: 16.0,
            block1_dither_switch: false,
            block1_dither_type: 0,

            block2_x_displace: 0.0,
            block2_y_displace: 0.0,
            block2_z_displace: 1.0,
            block2_rotate: 0.0,
            block2_shear_xx: 1.0,
            block2_shear_xy: 0.0,
            block2_shear_yx: 0.0,
            block2_shear_yy: 1.0,
            block2_kaleidoscope_amount: 0.0,
            block2_kaleidoscope_slice: 0.0,
            block2_h_mirror: false,
            block2_v_mirror: false,
            block2_rotate_mode: 0,
            block2_geo_overflow: 0,
            block2_h_flip: false,
            block2_v_flip: false,

            block2_colorize_switch: false,
            block2_colorize_hsb_rgb: 0,
            block2_colorize_band1_h: 0.0,
            block2_colorize_band1_s: 0.0,
            block2_colorize_band1_b: 0.0,
            block2_colorize_band2_h: 0.0,
            block2_colorize_band2_s: 0.0,
            block2_colorize_band2_b: 0.0,
            block2_colorize_band3_h: 0.0,
            block2_colorize_band3_s: 0.0,
            block2_colorize_band3_b: 0.0,
            block2_colorize_band4_h: 0.0,
            block2_colorize_band4_s: 0.0,
            block2_colorize_band4_b: 0.0,
            block2_colorize_band5_h: 0.0,
            block2_colorize_band5_s: 0.0,
            block2_colorize_band5_b: 0.0,

            block2_blur_amount: 0.0,
            block2_blur_radius: 1.0,
            block2_sharpen_amount: 0.0,
            block2_sharpen_radius: 1.0,
            block2_filters_boost: 0.0,
            block2_dither: 16.0,
            block2_dither_switch: false,
            block2_dither_type: 0,

            matrix_mix_type: 0,
            matrix_mix_overflow: 0,
            matrix_mix_r_to_r: 0.0,
            matrix_mix_r_to_g: 0.0,
            matrix_mix_r_to_b: 0.0,
            matrix_mix_g_to_r: 0.0,
            matrix_mix_g_to_g: 0.0,
            matrix_mix_g_to_b: 0.0,
            matrix_mix_b_to_r: 0.0,
            matrix_mix_b_to_g: 0.0,
            matrix_mix_b_to_b: 0.0,

            final_mix_amount: 0.0,
            final_key_value_r: 0.0,
            final_key_value_g: 0.0,
            final_key_value_b: 0.0,
            final_key_threshold: 1.0,
            final_key_soft: 0.0,
            final_mix_type: 0,
            final_mix_overflow: 0,
            final_key_order: 0,
            final_key_mode: 0,

            final_dither: 16.0,
            final_dither_switch: false,
            final_dither_type: 0,
        }
    }
}
